name: PyStan-Jupyter

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  tests:
    name: Install and test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.8]
      fail-fast: false
    steps:
      - name: Checkout github
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install python dependencies
        run: |
          pip install --upgrade pip
          pip install jupyterlab wheel
          pip install -r requirements.txt
      - name: Build wheel
        run: |
          python setup.py bdist_wheel
          pip install dist/*.whl
      - name: Run notebook
        run: |
          cd tests
          jupyter nbconvert --to notebook --inplace --ExecutePreprocessor.timeout=500 --execute example_pystan_jupyter.ipynb
  publish:
    name: Install and test
    runs-on: ${{ matrix.os }}
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8]
      fail-fast: false
    steps:
      - name: Upload wheels
        run: |
          pip install twine
          ls .
          ls dist
                    # twine upload --repository testpypi dist/*
        if: matrix.os == 'ubuntu-latest'
      - uses: actions/upload-artifact@v2
        with:
          name: wheel
          path: dist/
